# Generated by Django 4.1.1 on 2022-09-21 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('project', models.CharField(max_length=30)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 9, 21, 13, 37, 58, 526181, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
