# Generated by Django 4.1.1 on 2022-09-21 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 21, 14, 14, 2, 157419, tzinfo=datetime.timezone.utc)),
        ),
    ]
